version: '3.7'
services:
    db:
        image: 'mariadb:latest'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'kominiarczyk-app'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
        volumes:
            - 'mariadb-v:/var/lib/mysql'
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - "8085:80"
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=999M
        networks:
            - app-network
    nginx:
        build: .docker/nginx
        restart: unless-stopped
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
        depends_on:
            - php
        volumes:
            - .:/var/www/html
            - .docker/nginx/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
    redis:
        image: redis:latest
        restart: unless-stopped
        ports:
            - "7001:6379"
        networks:
            - app-network
    php:
        build: .docker/php-fpm
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - app-network
        ports:
            - "6001:6001"
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - .docker/project/.env.docker:/var/www/html/.env
            - .docker/project/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    mail:
        image: mailhog/mailhog:v1.0.0
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
volumes:
    mariadb-v:
        driver: local
